All: ex9-1.o Electronics.o Phone.o TV.o
	g++ -o 9-1 ex9-1.o Electronics.o Phone.o TV.o
Electronics.o: Electronics.cpp
	g++ Electronics.cpp -c 
Phone.o: Phone.cpp
	g++ Phone.cpp -c
TV.o: TV.cpp
	g++ TV.cpp -c
ex9-1: ex9-1.cpp
	g++ ex9-1.cpp -c
